"""Color palettes and color utility functions for cute robot avatar generation."""

from __future__ import annotations

from pydantic import BaseModel, Field


class ColorPalette(BaseModel):
    """A curated bright color palette for a cute robot avatar."""

    name: str
    description: str = ""
    background: str = Field(description="Main background color (hex)")
    background_alt: str = Field(description="Secondary background gradient color (hex)")
    chassis: str = Field(description="Main body and head color (hex)")
    chassis_dark: str = Field(description="Darker chassis shade for joints and shadow (hex)")
    chassis_outline: str = Field(
        default="#1E1E2F",
        description="High-contrast silhouette outline color (hex)",
    )
    faceplate: str = Field(description="Screen / faceplate background color (hex)")
    accent: str = Field(description="Accent color for ears, badges, antenna bulbs (hex)")
    eye_primary: str = Field(description="Primary eye color (hex)")
    eye_glow: str = Field(description="Specular eye shine or pupil color (hex)")
    mouth: str = Field(description="Mouth color (hex)")
    cheek: str = Field(description="Rosy blush cheek color (hex)")
    detail: str = Field(description="Bolts, lines, and hardware details (hex)")


PALETTES: dict[str, ColorPalette] = {
    "bubblegum": ColorPalette(
        name="bubblegum",
        description="Cheerful candy pinks, electric cyan, and soft yellow",
        background="#FFD6E8",
        background_alt="#FFB3D9",
        chassis="#FF6B9D",
        chassis_dark="#E04A7B",
        chassis_outline="#2B1020",
        faceplate="#FFFFFF",
        accent="#FFE66D",
        eye_primary="#4ECDC4",
        eye_glow="#FFFFFF",
        mouth="#E04A7B",
        cheek="#FF85A2",
        detail="#2B1020",
    ),
    "cyber_mint": ColorPalette(
        name="cyber_mint",
        description="Vibrant neon mint, electric cyan, and cyber magenta",
        background="#B8F2E6",
        background_alt="#84E6D2",
        chassis="#2EC4B6",
        chassis_dark="#1E9B8F",
        chassis_outline="#0A1E24",
        faceplate="#1A2238",
        accent="#FF3366",
        eye_primary="#48CAE4",
        eye_glow="#FFFFFF",
        mouth="#FF3366",
        cheek="#FF70A6",
        detail="#0A1E24",
    ),
    "sunny_lemon": ColorPalette(
        name="sunny_lemon",
        description="Bright sunshine yellow, warm coral, and sky cyan",
        background="#FFF3B0",
        background_alt="#FFE885",
        chassis="#FFD166",
        chassis_dark="#F4A261",
        chassis_outline="#2B1D0C",
        faceplate="#264653",
        accent="#EF476F",
        eye_primary="#06D6A0",
        eye_glow="#FFFFFF",
        mouth="#FFD166",
        cheek="#F78C6B",
        detail="#2B1D0C",
    ),
    "electric_berry": ColorPalette(
        name="electric_berry",
        description="Vivid magenta, electric violet, and bright lime",
        background="#F0E6FF",
        background_alt="#DBC4F0",
        chassis="#9B5DE5",
        chassis_dark="#7837C7",
        chassis_outline="#190730",
        faceplate="#1D1135",
        accent="#00F5D4",
        eye_primary="#F15BB5",
        eye_glow="#FFFFFF",
        mouth="#00F5D4",
        cheek="#F15BB5",
        detail="#190730",
    ),
    "neon_coral": ColorPalette(
        name="neon_coral",
        description="Bright warm coral, sunny gold, and cool teal",
        background="#FFE5D9",
        background_alt="#FFCAD4",
        chassis="#FF6F59",
        chassis_dark="#DB4C37",
        chassis_outline="#26100D",
        faceplate="#254441",
        accent="#43BCCD",
        eye_primary="#F6C85F",
        eye_glow="#FFFFFF",
        mouth="#43BCCD",
        cheek="#FF8E72",
        detail="#26100D",
    ),
    "aqua_splash": ColorPalette(
        name="aqua_splash",
        description="Deep ocean teal, electric turquoise, and lemon pop",
        background="#D0F4DE",
        background_alt="#A9DFBF",
        chassis="#00BBF9",
        chassis_dark="#0096C7",
        chassis_outline="#0A1D33",
        faceplate="#FFFFFF",
        accent="#FEE440",
        eye_primary="#00F5D4",
        eye_glow="#FFFFFF",
        mouth="#0096C7",
        cheek="#FF99C8",
        detail="#0A1D33",
    ),
    "lavender_sky": ColorPalette(
        name="lavender_sky",
        description="Pastel periwinkle, lavender, and peach cream",
        background="#E8EAFF",
        background_alt="#D0D5FF",
        chassis="#8338EC",
        chassis_dark="#6218CC",
        chassis_outline="#1C0D38",
        faceplate="#FFFFFF",
        accent="#FFBE0B",
        eye_primary="#3A86FF",
        eye_glow="#FFFFFF",
        mouth="#FB5607",
        cheek="#FF85A2",
        detail="#1C0D38",
    ),
    "emerald_bot": ColorPalette(
        name="emerald_bot",
        description="Electric lime, vivid emerald, and sunset orange",
        background="#E8F8F5",
        background_alt="#C8F2E7",
        chassis="#10B981",
        chassis_dark="#059669",
        chassis_outline="#06261C",
        faceplate="#0F172A",
        accent="#F59E0B",
        eye_primary="#38BDF8",
        eye_glow="#FFFFFF",
        mouth="#10B981",
        cheek="#F472B6",
        detail="#06261C",
    ),
    "arcade_pop": ColorPalette(
        name="arcade_pop",
        description="80s arcade neon pink, laser blue, and dark obsidian",
        background="#FCE7F3",
        background_alt="#FBCFE8",
        chassis="#EC4899",
        chassis_dark="#BE185D",
        chassis_outline="#1F0514",
        faceplate="#090A0F",
        accent="#06B6D4",
        eye_primary="#FACC15",
        eye_glow="#FFFFFF",
        mouth="#06B6D4",
        cheek="#F43F5E",
        detail="#1F0514",
    ),
    "cotton_candy": ColorPalette(
        name="cotton_candy",
        description="Soft pastel sky blue, strawberry milk, and golden vanilla",
        background="#E0F2FE",
        background_alt="#BAE6FD",
        chassis="#38BDF8",
        chassis_dark="#0284C7",
        chassis_outline="#0C2333",
        faceplate="#FFFFFF",
        accent="#F472B6",
        eye_primary="#6366F1",
        eye_glow="#FFFFFF",
        mouth="#0284C7",
        cheek="#FDA4AF",
        detail="#0C2333",
    ),
    "sunset_glow": ColorPalette(
        name="sunset_glow",
        description="Radiant tangerine, hot coral, and midnight navy",
        background="#FEF3C7",
        background_alt="#FDE68A",
        chassis="#FB923C",
        chassis_dark="#EA580C",
        chassis_outline="#2B1305",
        faceplate="#1E1B4B",
        accent="#A855F7",
        eye_primary="#38BDF8",
        eye_glow="#FFFFFF",
        mouth="#FDE047",
        cheek="#F43F5E",
        detail="#2B1305",
    ),
    "matcha_latte": ColorPalette(
        name="matcha_latte",
        description="Calm matcha green, creamy pistachio, and warm peach",
        background="#F0FDF4",
        background_alt="#DCFCE7",
        chassis="#84CC16",
        chassis_dark="#65A30D",
        chassis_outline="#162905",
        faceplate="#14532D",
        accent="#F97316",
        eye_primary="#FEF08A",
        eye_glow="#FFFFFF",
        mouth="#84CC16",
        cheek="#FB7185",
        detail="#162905",
    ),
    "vaporwave": ColorPalette(
        name="vaporwave",
        description="Pastel neon pink, cyan blue, and twilight purple",
        background="#F5D0FE",
        background_alt="#E879F9",
        chassis="#C084FC",
        chassis_dark="#9333EA",
        chassis_outline="#210838",
        faceplate="#2E1065",
        accent="#22D3EE",
        eye_primary="#F43F5E",
        eye_glow="#FFFFFF",
        mouth="#22D3EE",
        cheek="#F472B6",
        detail="#210838",
    ),
    "solar_flare": ColorPalette(
        name="solar_flare",
        description="Blazing crimson red, solar yellow, and fiery orange",
        background="#FEE2E2",
        background_alt="#FECACA",
        chassis="#EF4444",
        chassis_dark="#DC2626",
        chassis_outline="#3B0808",
        faceplate="#450A0A",
        accent="#FACC15",
        eye_primary="#38BDF8",
        eye_glow="#FFFFFF",
        mouth="#FDE047",
        cheek="#FB923C",
        detail="#3B0808",
    ),
    "tokyo_night": ColorPalette(
        name="tokyo_night",
        description="Electric cyan, neon violet, and night obsidian",
        background="#E0E7FF",
        background_alt="#C7D2FE",
        chassis="#6366F1",
        chassis_dark="#4338CA",
        chassis_outline="#101033",
        faceplate="#0B0F19",
        accent="#F43F5E",
        eye_primary="#06B6D4",
        eye_glow="#FFFFFF",
        mouth="#F43F5E",
        cheek="#FB7185",
        detail="#101033",
    ),
    "bumblebee": ColorPalette(
        name="bumblebee",
        description="Bright bumblebee yellow, jet black, and warm amber",
        background="#FEF9C3",
        background_alt="#FEF08A",
        chassis="#EAB308",
        chassis_dark="#CA8A04",
        chassis_outline="#1C1502",
        faceplate="#18181B",
        accent="#F97316",
        eye_primary="#38BDF8",
        eye_glow="#FFFFFF",
        mouth="#EAB308",
        cheek="#FB923C",
        detail="#1C1502",
    ),
    "aurora_borealis": ColorPalette(
        name="aurora_borealis",
        description="Shimmering emerald, polar cyan, and celestial violet",
        background="#CCFBF1",
        background_alt="#99F6E4",
        chassis="#14B8A6",
        chassis_dark="#0D9488",
        chassis_outline="#052420",
        faceplate="#042F2E",
        accent="#A855F7",
        eye_primary="#67E8F9",
        eye_glow="#FFFFFF",
        mouth="#67E8F9",
        cheek="#F472B6",
        detail="#052420",
    ),
    "cherry_blossom": ColorPalette(
        name="cherry_blossom",
        description="Soft sakura pink, rose crimson, and ivory cream",
        background="#FFF1F2",
        background_alt="#FFE4E6",
        chassis="#FB7185",
        chassis_dark="#E11D48",
        chassis_outline="#330914",
        faceplate="#4C0519",
        accent="#FBBF24",
        eye_primary="#34D399",
        eye_glow="#FFFFFF",
        mouth="#FBBF24",
        cheek="#FDA4AF",
        detail="#330914",
    ),
    "poison_ivy": ColorPalette(
        name="poison_ivy",
        description="Neon slime green, toxic lime, and electric violet",
        background="#ECFCCB",
        background_alt="#D9F99D",
        chassis="#65A30D",
        chassis_dark="#4D7C0F",
        chassis_outline="#1A2E05",
        faceplate="#1A2E05",
        accent="#C084FC",
        eye_primary="#A3E635",
        eye_glow="#FFFFFF",
        mouth="#C084FC",
        cheek="#F472B6",
        detail="#1A2E05",
    ),
    "glacier_ice": ColorPalette(
        name="glacier_ice",
        description="Ice crystal cyan, frost blue, and arctic snow",
        background="#CFFAFE",
        background_alt="#A5F3FC",
        chassis="#06B6D4",
        chassis_dark="#0891B2",
        chassis_outline="#06222B",
        faceplate="#083344",
        accent="#F59E0B",
        eye_primary="#67E8F9",
        eye_glow="#FFFFFF",
        mouth="#67E8F9",
        cheek="#F472B6",
        detail="#06222B",
    ),
    "papaya_punch": ColorPalette(
        name="papaya_punch",
        description="Tropical papaya orange, guava pink, and palm green",
        background="#FFEDD5",
        background_alt="#FED7AA",
        chassis="#F97316",
        chassis_dark="#EA580C",
        chassis_outline="#331405",
        faceplate="#431407",
        accent="#10B981",
        eye_primary="#FDE047",
        eye_glow="#FFFFFF",
        mouth="#10B981",
        cheek="#FB7185",
        detail="#331405",
    ),
    "cyberpunk_2077": ColorPalette(
        name="cyberpunk_2077",
        description="High-voltage electric neon yellow, hot magenta, and laser cyan",
        background="#FEF08A",
        background_alt="#FDE047",
        chassis="#FACC15",
        chassis_dark="#CA8A04",
        chassis_outline="#0A0A14",
        faceplate="#090A0F",
        accent="#F43F5E",
        eye_primary="#00F5D4",
        eye_glow="#FFFFFF",
        mouth="#00F5D4",
        cheek="#F43F5E",
        detail="#0A0A14",
    ),
    "abyssal_deep": ColorPalette(
        name="abyssal_deep",
        description="Bioluminescent deep sea aqua, midnight navy, and electric cyan",
        background="#0F172A",
        background_alt="#1E293B",
        chassis="#0284C7",
        chassis_dark="#0369A1",
        chassis_outline="#030712",
        faceplate="#082F49",
        accent="#00F5D4",
        eye_primary="#38BDF8",
        eye_glow="#FFFFFF",
        mouth="#00F5D4",
        cheek="#38BDF8",
        detail="#030712",
    ),
    "strawberry_matcha": ColorPalette(
        name="strawberry_matcha",
        description="Sweet strawberry red-pink, matcha cream green, and vanilla",
        background="#FDF2F8",
        background_alt="#FCE7F3",
        chassis="#F43F5E",
        chassis_dark="#E11D48",
        chassis_outline="#330612",
        faceplate="#14532D",
        accent="#84CC16",
        eye_primary="#FEF08A",
        eye_glow="#FFFFFF",
        mouth="#84CC16",
        cheek="#FDA4AF",
        detail="#330612",
    ),
    "galaxy_nebula": ColorPalette(
        name="galaxy_nebula",
        description="Cosmic deep indigo, stellar purple, and hot starlight pink",
        background="#1E1B4B",
        background_alt="#312E81",
        chassis="#7C3AED",
        chassis_dark="#6D28D9",
        chassis_outline="#0B0726",
        faceplate="#0F172A",
        accent="#F43F5E",
        eye_primary="#38BDF8",
        eye_glow="#FFFFFF",
        mouth="#F472B6",
        cheek="#F43F5E",
        detail="#0B0726",
    ),
    "mint_chocolate": ColorPalette(
        name="mint_chocolate",
        description="Cool fresh spearmint, rich dark cocoa, and crisp white",
        background="#E6FFFA",
        background_alt="#B2F5EA",
        chassis="#38B2AC",
        chassis_dark="#319795",
        chassis_outline="#231709",
        faceplate="#3D2612",
        accent="#F6AD55",
        eye_primary="#81E6D9",
        eye_glow="#FFFFFF",
        mouth="#81E6D9",
        cheek="#F687B3",
        detail="#231709",
    ),
    "golden_hour": ColorPalette(
        name="golden_hour",
        description="Warm amber gold, honey yellow, and rich terracotta",
        background="#FFFBEB",
        background_alt="#FEF3C7",
        chassis="#F59E0B",
        chassis_dark="#D97706",
        chassis_outline="#2E1503",
        faceplate="#451A03",
        accent="#EF4444",
        eye_primary="#FDE047",
        eye_glow="#FFFFFF",
        mouth="#FDE047",
        cheek="#FB923C",
        detail="#2E1503",
    ),
    "synthwave_sunset": ColorPalette(
        name="synthwave_sunset",
        description="Neon violet sky, sunset orange, and laser cyan",
        background="#FDF4FF",
        background_alt="#FAE8FF",
        chassis="#A855F7",
        chassis_dark="#9333EA",
        chassis_outline="#1E0533",
        faceplate="#18002E",
        accent="#F97316",
        eye_primary="#06B6D4",
        eye_glow="#FFFFFF",
        mouth="#06B6D4",
        cheek="#F43F5E",
        detail="#1E0533",
    ),
    "pistachio_cream": ColorPalette(
        name="pistachio_cream",
        description="Soft pistachio green, buttercream yellow, and sweet raspberry",
        background="#F7FEE7",
        background_alt="#ECFCCB",
        chassis="#A3E635",
        chassis_dark="#84CC16",
        chassis_outline="#1C2B05",
        faceplate="#365314",
        accent="#F43F5E",
        eye_primary="#FEF08A",
        eye_glow="#FFFFFF",
        mouth="#FEF08A",
        cheek="#FB7185",
        detail="#1C2B05",
    ),
    "grape_soda": ColorPalette(
        name="grape_soda",
        description="Sparkling fizzy grape purple, neon lime green, and violet",
        background="#F3E8FF",
        background_alt="#E9D5FF",
        chassis="#9333EA",
        chassis_dark="#7E22CE",
        chassis_outline="#1C0633",
        faceplate="#240046",
        accent="#84CC16",
        eye_primary="#A855F7",
        eye_glow="#FFFFFF",
        mouth="#84CC16",
        cheek="#F472B6",
        detail="#1C0633",
    ),
    "blueberry_muffin": ColorPalette(
        name="blueberry_muffin",
        description="Warm blueberry indigo, buttery golden crumb, and vanilla cream",
        background="#EEF2FF",
        background_alt="#E0E7FF",
        chassis="#4F46E5",
        chassis_dark="#4338CA",
        chassis_outline="#0F0C33",
        faceplate="#1E1B4B",
        accent="#F59E0B",
        eye_primary="#60A5FA",
        eye_glow="#FFFFFF",
        mouth="#FDE047",
        cheek="#F472B6",
        detail="#0F0C33",
    ),
    "lava_magma": ColorPalette(
        name="lava_magma",
        description="Molten glowing orange, obsidian charcoal, and volcanic crimson",
        background="#FFF7ED",
        background_alt="#FFEDD5",
        chassis="#EA580C",
        chassis_dark="#C2410C",
        chassis_outline="#2B0A02",
        faceplate="#1C1917",
        accent="#E11D48",
        eye_primary="#FACC15",
        eye_glow="#FFFFFF",
        mouth="#FACC15",
        cheek="#FB923C",
        detail="#2B0A02",
    ),
    "peaches_and_cream": ColorPalette(
        name="peaches_and_cream",
        description="Soft peach coral, rich cream ivory, and sweet apricot",
        background="#FFF1F2",
        background_alt="#FFE4E6",
        chassis="#FB923C",
        chassis_dark="#F97316",
        chassis_outline="#331405",
        faceplate="#FFFFFF",
        accent="#F43F5E",
        eye_primary="#FB7185",
        eye_glow="#FFFFFF",
        mouth="#F97316",
        cheek="#FDA4AF",
        detail="#331405",
    ),
    "arctic_fox": ColorPalette(
        name="arctic_fox",
        description="Frosted icy white, soft sky blue, and arctic navy",
        background="#F0F9FF",
        background_alt="#E0F2FE",
        chassis="#0284C7",
        chassis_dark="#0369A1",
        chassis_outline="#08253B",
        faceplate="#FFFFFF",
        accent="#38BDF8",
        eye_primary="#0369A1",
        eye_glow="#FFFFFF",
        mouth="#0284C7",
        cheek="#93C5FD",
        detail="#08253B",
    ),
    "dragonfruit": ColorPalette(
        name="dragonfruit",
        description="Neon fuchsia dragonfruit pink, kiwi seed green, and white",
        background="#FDF2F8",
        background_alt="#FCE7F3",
        chassis="#DB2777",
        chassis_dark="#BE185D",
        chassis_outline="#2E0419",
        faceplate="#18181B",
        accent="#84CC16",
        eye_primary="#06B6D4",
        eye_glow="#FFFFFF",
        mouth="#84CC16",
        cheek="#F472B6",
        detail="#2E0419",
    ),
    "caramel_latte": ColorPalette(
        name="caramel_latte",
        description="Warm caramel brown, rich espresso, and golden vanilla",
        background="#FEF3C7",
        background_alt="#FDE68A",
        chassis="#B45309",
        chassis_dark="#92400E",
        chassis_outline="#261002",
        faceplate="#451A03",
        accent="#F59E0B",
        eye_primary="#FDE047",
        eye_glow="#FFFFFF",
        mouth="#FDE047",
        cheek="#F97316",
        detail="#261002",
    ),
    "hyper_lime": ColorPalette(
        name="hyper_lime",
        description="High-voltage electric neon lime, black, and turquoise",
        background="#F7FEE7",
        background_alt="#ECFCCB",
        chassis="#84CC16",
        chassis_dark="#65A30D",
        chassis_outline="#0D1A02",
        faceplate="#090A0F",
        accent="#06B6D4",
        eye_primary="#A3E635",
        eye_glow="#FFFFFF",
        mouth="#06B6D4",
        cheek="#A3E635",
        detail="#0D1A02",
    ),
    "tropic_paradise": ColorPalette(
        name="tropic_paradise",
        description="Bright mango yellow, Caribbean ocean turquoise, and hibiscus red",
        background="#FEF9C3",
        background_alt="#FEF08A",
        chassis="#06B6D4",
        chassis_dark="#0891B2",
        chassis_outline="#04202B",
        faceplate="#083344",
        accent="#EF4444",
        eye_primary="#FACC15",
        eye_glow="#FFFFFF",
        mouth="#EF4444",
        cheek="#F87171",
        detail="#04202B",
    ),
    "midnight_prism": ColorPalette(
        name="midnight_prism",
        description="Deep midnight void, iridescent cyan, and magenta shimmer",
        background="#0F172A",
        background_alt="#1E293B",
        chassis="#6366F1",
        chassis_dark="#4F46E5",
        chassis_outline="#040614",
        faceplate="#020617",
        accent="#EC4899",
        eye_primary="#22D3EE",
        eye_glow="#FFFFFF",
        mouth="#22D3EE",
        cheek="#F472B6",
        detail="#040614",
    ),
    "candy_corn": ColorPalette(
        name="candy_corn",
        description="Warm candy corn gold, pumpkin orange, vanilla white, and chocolate",
        background="#FEF3C7",
        background_alt="#FDE68A",
        chassis="#F59E0B",
        chassis_dark="#D97706",
        chassis_outline="#2B1402",
        faceplate="#451A03",
        accent="#EA580C",
        eye_primary="#FEF08A",
        eye_glow="#FFFFFF",
        mouth="#FEF08A",
        cheek="#FB923C",
        detail="#2B1402",
    ),
}


def _safe_rgba(val: object) -> tuple[int, int, int, int]:
    """Safely convert any PIL getpixel return value into an RGBA 4-tuple."""
    if isinstance(val, (tuple, list)):
        r = int(val[0])
        g = int(val[1]) if len(val) > 1 else r
        b = int(val[2]) if len(val) > 2 else r
        a = int(val[3]) if len(val) > 3 else 255
        return (r, g, b, a)
    num = int(val) if isinstance(val, (int, float)) else 0
    return (num, num, num, 255)


def list_palettes() -> list[str]:
    """Return a sorted list of all available palette names."""
    return sorted(PALETTES.keys())


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Convert a hex color string (e.g. '#FF6B9D' or 'FF6B9D') to an (R, G, B) tuple."""
    clean_hex = hex_color.lstrip("#")
    if len(clean_hex) == 3:
        clean_hex = "".join(c * 2 for c in clean_hex)
    if len(clean_hex) != 6:
        msg = f"Invalid hex color: '{hex_color}'"
        raise ValueError(msg)
    r = int(clean_hex[0:2], 16)
    g = int(clean_hex[2:4], 16)
    b = int(clean_hex[4:6], 16)
    return (r, g, b)


def hex_to_rgba(hex_color: str, alpha: int = 255) -> tuple[int, int, int, int]:
    """Convert a hex color string to an (R, G, B, A) tuple."""
    r, g, b = hex_to_rgb(hex_color)
    return (r, g, b, alpha)


def get_palette(name: str) -> ColorPalette:
    """Retrieve a palette by name. Raises ValueError if name is unknown."""
    normalized = name.lower().replace("-", "_").strip()
    if normalized not in PALETTES:
        available = ", ".join(sorted(PALETTES.keys()))
        msg = f"Unknown palette '{name}'. Available palettes: {available}"
        raise ValueError(msg)
    return PALETTES[normalized]
